# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

lf () { ls -CFa | more $* ; }
ll () { ls -la | more $* ; }
lt () { ls -lat $* | more ; }


# Source global definitions
[[ -f /etc/bashrc ]] && source /etc/bashrc

cowsay "Hello there, $USER!!! ;-)"
